### ISSUE TITLE
htaccesscode

### ISSUE THREAD

**Issue by thennavan-dev** [Kesavan-Hex/webpage-load-testing#1]

**Comment by Kesavan-Hex** [comment]
http://www.yourdomain.com/
| -- directory1
| -- directory2
| -- directory3
|    | -- directory3/childdirectory1
|    | -- directory3/childdirectory2
| -- .htaccess
| -- index.html




RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www.yourdomain.com [NC]
RewriteRule ^(.*)$ http://yourdomain.com/$1 [L,R=301]
